package com.example.pokemonshinytracker

import android.content.ContentValues
import android.database.sqlite.SQLiteDatabase
import android.util.Log

data class Pokemon(val pokemonID: Int, val pokemonName: String, val pokemonImage: Int)

object PokemonData {
    fun insertPokemonData(db: SQLiteDatabase, POKEMON_TABLE: String, POKEMON_NAME_COL: String, POKEMON_IMAGE_COL: String) {
        val pokemonList = listOf(
            "Default" to R.drawable.etc_default,
            "Bulbasaur" to R.drawable.pokemon_1_bulbasaur,
            "Ivysaur" to R.drawable.pokemon_2_ivysaur,
            "Venusaur" to R.drawable.pokemon_3_venusaur,
            "Charmander" to R.drawable.pokemon_4_charmander,
            "Charmeleon" to R.drawable.pokemon_5_charmeleon,
            "Charizard" to R.drawable.pokemon_6_charizard,
            "Squirtle" to R.drawable.pokemon_7_squirtle,
            "Wartortle" to R.drawable.pokemon_8_wartortle,
            "Blastoise" to R.drawable.pokemon_9_blastoise,
            "Caterpie" to R.drawable.pokemon_10_caterpie,
            "Metapod" to R.drawable.pokemon_11_metapod,
            "Butterfree" to R.drawable.pokemon_12_butterfree,
            "Weedle" to R.drawable.pokemon_13_weedle,
            "Kakuna" to R.drawable.pokemon_14_kakuna,
            "Beedrill" to R.drawable.pokemon_15_beedrill,
            "Pidgey" to R.drawable.pokemon_16_pidgey,
            "Pidgeotto" to R.drawable.pokemon_17_pidgeotto,
            "Pidgeot" to R.drawable.pokemon_18_pidgeot,
            "Rattata" to R.drawable.pokemon_19_rattata,
            "Raticate" to R.drawable.pokemon_20_raticate,
            "Spearow" to R.drawable.pokemon_21_spearow,
            "Fearow" to R.drawable.pokemon_22_fearow,
            "Ekans" to R.drawable.pokemon_23_ekans,
            "Arbok" to R.drawable.pokemon_24_arbok,
            "Pikachu" to R.drawable.pokemon_25_pikachu,
            "Raichu" to R.drawable.pokemon_26_raichu,
            "Sandshrew" to R.drawable.pokemon_27_sandshrew,
            "Sandslash" to R.drawable.pokemon_28_sandslash,
            "Nidoran♀" to R.drawable.pokemon_29_nidoranf,
            "Nidorina" to R.drawable.pokemon_30_nidorina,
            "Nidoqueen" to R.drawable.pokemon_31_nidoqueen,
            "Nidoran♂" to R.drawable.pokemon_32_nidoranm,
            "Nidorino" to R.drawable.pokemon_33_nidorino,
            "Nidoking" to R.drawable.pokemon_34_nidoking,
            "Clefairy" to R.drawable.pokemon_35_clefairy,
            "Clefable" to R.drawable.pokemon_36_clefable,
            "Vulpix" to R.drawable.pokemon_37_vulpix,
            "Ninetales" to R.drawable.pokemon_38_ninetales,
            "Jigglypuff" to R.drawable.pokemon_39_jigglypuff,
            "Wigglytuff" to R.drawable.pokemon_40_wigglytuff,
            "Zubat" to R.drawable.pokemon_41_zubat,
            "Golbat" to R.drawable.pokemon_42_golbat,
            "Oddish" to R.drawable.pokemon_43_oddish,
            "Gloom" to R.drawable.pokemon_44_gloom,
            "Vileplume" to R.drawable.pokemon_45_vileplume,
            "Paras" to R.drawable.pokemon_46_paras,
            "Parasect" to R.drawable.pokemon_47_parasect,
            "Venonat" to R.drawable.pokemon_48_venonat,
            "Venomoth" to R.drawable.pokemon_49_venomoth,
            "Diglett" to R.drawable.pokemon_50_diglett,
            "Dugtrio" to R.drawable.pokemon_51_dugtrio,
            "Meowth" to R.drawable.pokemon_52_meowth,
            "Persian" to R.drawable.pokemon_53_persian,
            "Psyduck" to R.drawable.pokemon_54_psyduck,
            "Golduck" to R.drawable.pokemon_55_golduck,
            "Mankey" to R.drawable.pokemon_56_mankey,
            "Primeape" to R.drawable.pokemon_57_primeape,
            "Growlithe" to R.drawable.pokemon_58_growlithe,
            "Arcanine" to R.drawable.pokemon_59_arcanine,
            "Poliwag" to R.drawable.pokemon_60_poliwag,
            "Poliwhirl" to R.drawable.pokemon_61_poliwhirl,
            "Poliwrath" to R.drawable.pokemon_62_poliwrath,
            "Abra" to R.drawable.pokemon_63_abra,
            "Kadabra" to R.drawable.pokemon_64_kadabra,
            "Alakazam" to R.drawable.pokemon_65_alakazam,
            "Machop" to R.drawable.pokemon_66_machop,
            "Machoke" to R.drawable.pokemon_67_machoke,
            "Machamp" to R.drawable.pokemon_68_machamp,
            "Bellsprout" to R.drawable.pokemon_69_bellsprout,
            "Weepinbell" to R.drawable.pokemon_70_weepinbell,
            "Victreebel" to R.drawable.pokemon_71_victreebel,
            "Tentacool" to R.drawable.pokemon_72_tentacool,
            "Tentacruel" to R.drawable.pokemon_73_tentacruel,
            "Geodude" to R.drawable.pokemon_74_geodude,
            "Graveler" to R.drawable.pokemon_75_graveler,
            "Golem" to R.drawable.pokemon_76_golem,
            "Ponyta" to R.drawable.pokemon_77_ponyta,
            "Rapidash" to R.drawable.pokemon_78_rapidash,
            "Slowpoke" to R.drawable.pokemon_79_slowpoke,
            "Slowbro" to R.drawable.pokemon_80_slowbro,
            "Magnemite" to R.drawable.pokemon_81_magnemite,
            "Magneton" to R.drawable.pokemon_82_magneton,
            "Farfetch'd" to R.drawable.pokemon_83_farfetchd,
            "Doduo" to R.drawable.pokemon_84_doduo,
            "Dodrio" to R.drawable.pokemon_85_dodrio,
            "Seel" to R.drawable.pokemon_86_seel,
            "Dewgong" to R.drawable.pokemon_87_dewgong,
            "Grimer" to R.drawable.pokemon_88_grimer,
            "Muk" to R.drawable.pokemon_89_muk,
            "Shellder" to R.drawable.pokemon_90_shellder,
            "Cloyster" to R.drawable.pokemon_91_cloyster,
            "Gastly" to R.drawable.pokemon_92_gastly,
            "Haunter" to R.drawable.pokemon_93_haunter,
            "Gengar" to R.drawable.pokemon_94_gengar,
            "Onix" to R.drawable.pokemon_95_onix,
            "Drowzee" to R.drawable.pokemon_96_drowzee,
            "Hypno" to R.drawable.pokemon_97_hypno,
            "Krabby" to R.drawable.pokemon_98_krabby,
            "Kingler" to R.drawable.pokemon_99_kingler,
            "Voltorb" to R.drawable.pokemon_100_voltorb,
            "Electrode" to R.drawable.pokemon_101_electrode,
            "Exeggcute" to R.drawable.pokemon_102_exeggcute,
            "Exeggutor" to R.drawable.pokemon_103_exeggutor,
            "Cubone" to R.drawable.pokemon_104_cubone,
            "Marowak" to R.drawable.pokemon_105_marowak,
            "Hitmonlee" to R.drawable.pokemon_106_hitmonlee,
            "Hitmonchan" to R.drawable.pokemon_107_hitmonchan,
            "Lickitung" to R.drawable.pokemon_108_lickitung,
            "Koffing" to R.drawable.pokemon_109_koffing,
            "Weezing" to R.drawable.pokemon_110_weezing,
            "Rhyhorn" to R.drawable.pokemon_111_rhyhorn,
            "Rhydon" to R.drawable.pokemon_112_rhydon,
            "Chansey" to R.drawable.pokemon_113_chansey,
            "Tangela" to R.drawable.pokemon_114_tangela,
            "Kangaskhan" to R.drawable.pokemon_115_kangaskhan,
            "Horsea" to R.drawable.pokemon_116_horsea,
            "Seadra" to R.drawable.pokemon_117_seadra,
            "Goldeen" to R.drawable.pokemon_118_goldeen,
            "Seaking" to R.drawable.pokemon_119_seaking,
            "Staryu" to R.drawable.pokemon_120_staryu,
            "Starmie" to R.drawable.pokemon_121_starmie,
            "Mrmime" to R.drawable.pokemon_122_mrmime,
            "Scyther" to R.drawable.pokemon_123_scyther,
            "Jynx" to R.drawable.pokemon_124_jynx,
            "Electabuzz" to R.drawable.pokemon_125_electabuzz,
            "Magmar" to R.drawable.pokemon_126_magmar,
            "Pinsir" to R.drawable.pokemon_127_pinsir,
            "Tauros" to R.drawable.pokemon_128_tauros,
            "Magikarp" to R.drawable.pokemon_129_magikarp,
            "Gyarados" to R.drawable.pokemon_130_gyarados,
            "Lapras" to R.drawable.pokemon_131_lapras,
            "Ditto" to R.drawable.pokemon_132_ditto,
            "Eevee" to R.drawable.pokemon_133_eevee,
            "Vaporeon" to R.drawable.pokemon_134_vaporeon,
            "Jolteon" to R.drawable.pokemon_135_jolteon,
            "Flareon" to R.drawable.pokemon_136_flareon,
            "Porygon" to R.drawable.pokemon_137_porygon,
            "Omanyte" to R.drawable.pokemon_138_omanyte,
            "Omastar" to R.drawable.pokemon_139_omastar,
            "Kabuto" to R.drawable.pokemon_140_kabuto,
            "Kabutops" to R.drawable.pokemon_141_kabutops,
            "Aerodactyl" to R.drawable.pokemon_142_aerodactyl,
            "Snorlax" to R.drawable.pokemon_143_snorlax,
            "Articuno" to R.drawable.pokemon_144_articuno,
            "Zapdos" to R.drawable.pokemon_145_zapdos,
            "Moltres" to R.drawable.pokemon_146_moltres,
            "Dratini" to R.drawable.pokemon_147_dratini,
            "Dragonair" to R.drawable.pokemon_148_dragonair,
            "Dragonite" to R.drawable.pokemon_149_dragonite,
            "Mewtwo" to R.drawable.pokemon_150_mewtwo,
            "Mew" to R.drawable.pokemon_151_mew
        )

        for ((name, image) in pokemonList) {
            val values = ContentValues().apply {
                put(POKEMON_NAME_COL, name)
                put(POKEMON_IMAGE_COL, image)
            }
            db.insert(POKEMON_TABLE, null, values)
            Log.d("PokemonModel", "Pokemon \"$name\" inserted into the database")
        }
        Log.d("PokemonData", "All Pokemon have been inserted into the database")
    }
}